language: node_js
node_js:
- "10"
sudo: required
before_install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
before_script:
- npm install
- git clone https://${GH_TOKEN}@github.com/EmilyHill94/emilyhill94.github.io
  public
cache:
  directories:
  - node_modules
script:
- npm run scss
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
env:
  global:
    secure: uAGujF6j9d1vQKKDaL2l/5vOjNC8RD+h7sdyqfFr3ys0vFSgBJSbFqGwVweubX68qpitVCwwUR7MTm+HWiUQePiiQzeT764SBZ78+45uK521W6RnaTFDQrouR8woftxx/FjfGHaT5sEucac9aEtVyAaxVUV6cozgepQwJCiMGBmzdt2uPa21eJ0Ibv40vNzm4kaSRuUB5j7/iggqsVQWxkqbRmrxCDrjLoe1t105uJDiLUxmBGgr83Tc8MYm1g1BlR8mQvuFB/71siSiJVUPpGDZLIlz7ysbRnKMOqQuxZsovMjVmm1ICY6jHVxznubsZ6t+yIKk7gv0corN4j6+XpPXVzzCl0Qv0V4EBzOrBtAxBuRBmReOX0ATsWJX2wqrWTZ/UZZsbmVkQDxZGypovrZiVB/OVIWG0XsCEDoWegu7Hj2ayLwIbukiByrJblov3JW0rPp/nyyO4L3brFAmoiwM3e48RnESaR6Raanr6oxVns7FBWWJYdxx2D9Ptd1XCd0sSKA16imaePbHtFiQTEXXDu4Dqh7nI1PaRhq+SgXhQ8rN9yzl2s9LT2du5tCtl1r9tICarqoLC+uh2gBW/7aptTfTuTxwUIeoTF9BWWAS2Fsaqba3cEKTj4NL2EV827pUq0afa0ecy5JRCzynp0Q+2aRJovdvKplsTy0PJys=
