language: node_js
node_js:
  - "node"

sudo: required

before_install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

before_script:
  - npm install
  - git clone https://github.com/digital-land/digital-land.github.io.git public

cache:
  directories:
    - "node_modules"

script:
  - npm run build

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
