baseURL = "https://digital-land.cloudapps.digital/"
languageCode = "en-uk"
title = "Digital Land"
theme = "govuk"

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
  servicename = "Digital Land"
    users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Portfolio"
  url = "/portfolio"
  currentpage = true

  [[params.propositionlinks]]
  name = "Collector"
  url = "/prototype/digital-land-collector/"

  [[params.propositionlinks]]
  name = "Explorer"
  url = "/prototype/digital-land-explorer/"

  [[params.propositionlinks]]
  name = "Prototypes"
  url = "/prototype/"

  [[params.propositionlinks]]
  name = "Guidance"
  url = "/glossary/"

  [[params.propositionlinks]]
  name = "Users"
  url = "/users/"

[taxonomies]
  tag = "tags"
  pattern = "patterns"