baseURL = "https://digital-land.cloudapps.digital/"
languageCode = "en-uk"
title = "Digital Land"
theme = "govuk"

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
	servicename = "Digital Land"
    users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Portfolio"
  url = "/portfolio"
  currentpage = true

  [[params.propositionlinks]]
  name = "Section 106 and Viability Assessments"
  url = "https://section-106-prototype.cloudapps.digital/"

[taxonomies]
  tag = "tags"
  pattern = "patterns"
