baseURL = "https://digital-land.github.io/"
languageCode = "en-uk"
title = "Digital Land"
theme = "govuk"
googleAnalytics = "UA-127566551-1"

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
  servicename = "Digital Land"
    users = ["Data Maintainer", "Data Modeller", "Policy Maker", "PropTech"]

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Portfolio"
  url = "/portfolio"
  currentpage = true

  [[params.propositionlinks]]
  name = "Projects"
  url = "/project/"

  [[params.propositionlinks]]
  name = "Prototypes"
  url = "/prototype/"

  [[params.propositionlinks]]
  name = "Guidance"
  url = "/glossary/"

  [[params.propositionlinks]]
  name = "Users"
  url = "/users/"

[taxonomies]
  tag = "tags"
  pattern = "patterns"
