baseURL = "https://digital-land-portfolio.cloudapps.digital/"
languageCode = "en-uk"
title = "Digital Land Pattern Portfolio"
theme = "govuk"

staticDir = ["static", "src/govuk_template/assets", "src/govuk_elements/assets"]

[params]
	servicename = "Digital Land Services"

  # Nav links in the side bar
  [[params.propositionlinks]]
  name = "Portfolio"
  url = "/portfolio"
  currentpage = true

  [[params.propositionlinks]]
  name = "Data Explorer"
  url = "https://digital-land-explorer.cloudapps.digital/"

  [[params.propositionlinks]]
  name = "Prototypes"
  url = "https://section-106-prototype.cloudapps.digital/"

[taxonomies]
  tag = "tags"
  pattern = "patterns"