baseURL = "https://digital-land-portfolio.cloudapps.digital/"
languageCode = "en-uk"
title = "Digital Land Pattern Portfolio"
theme = "govuk"

staticDir = ["static", "src/govuk_template/assets"]

[params]
	servicename = "Digital Land Services"